C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
Coup(1) * (P(-1,1)*P(-1,1)*Metric(1,2)) + Coup(2) * (P(1,1)*P(2,1))
C     
      SUBROUTINE R2_GG_1_R2_GG_2_0(V1, V2, COUP1, COUP2,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP1
      COMPLEX*16 COUP2
      COMPLEX*16 P1(0:3)
      COMPLEX*16 TMP11
      COMPLEX*16 TMP12
      COMPLEX*16 TMP4
      COMPLEX*16 TMP6
      COMPLEX*16 V1(*)
      COMPLEX*16 V2(*)
      COMPLEX*16 VERTEX
      P1(0) = V1(1)
      P1(1) = V1(2)
      P1(2) = V1(3)
      P1(3) = V1(4)
      TMP11 = (P1(0)*P1(0)-P1(1)*P1(1)-P1(2)*P1(2)-P1(3)*P1(3))
      TMP12 = (P1(0)*V1(5)-P1(1)*V1(6)-P1(2)*V1(7)-P1(3)*V1(8))
      TMP4 = (V2(5)*V1(5)-V2(6)*V1(6)-V2(7)*V1(7)-V2(8)*V1(8))
      TMP6 = (V2(5)*P1(0)-V2(6)*P1(1)-V2(7)*P1(2)-V2(8)*P1(3))
      VERTEX = (-1D0)*(+CI*(TMP4*TMP11*COUP1+TMP6*TMP12*COUP2))
      END


