C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Identity(1,2)
C     
      SUBROUTINE R2_QQ_2_0(F1, F2, COUP,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 TMP14
      COMPLEX*16 VERTEX
      TMP14 = (F2(5)*F1(5)+F2(6)*F1(6)+F2(7)*F1(7)+F2(8)*F1(8))
      VERTEX = COUP*(-CI * TMP14)
      END


